# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc65d3427552e02df272f3e4b80146af5f45e20ef6b55db5529d1bf0ce936b765c0c599405ed6a77c44b17d8ed2f6bc0a2411861f4146dad80addf141e48d709

test:
  secret_key_base: 7f01a2b70f51c9b8e25c3b6720a7462e7507e59497a231326c6ded9cd81d22753e87e9b98462b97d52150eb9ef16c9ba6d9cb0e997671100815cb75ff1c9fca7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
